title: Stack Problems
description: My Personal Stack Problems
author: Supravat Mondal
github: https://github.com/supravatm
about: "I am Software Developer with multiple framework skills like PHP, Magento 1, Magento 2, Laravel, CakePHP, API Integration(SOAP, REST, SAP) Jquery, Ajax, Javascript and many more to learn"
disqus_shortname: supravatm
google_analytics: UA-144666263-1
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/supravatm.github.io"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/supravat/"
    - icon: fa-stack-exchange
      link: "https://magento.stackexchange.com/users/3368/supravat-m"
    - icon: fa-github
      link: "https://github.com/supravatm"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://supravatm.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
