title: Supravat Mondal
logo: /assets/img/supravat-mondal-logo-picture.webp
email: supravat.com@gmail.com
description: SDE @ Open. Adobe-Commerce(Magento 2)
favicon: true
remote_theme: supravatm/jekyll-theme-minimalistic
color-scheme: light

google_analytics: GTM-WSTTQ659

url: "https://github.com/supravatm/"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Resume
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/files/Adobe-Commerce-Engineer-Supravat-Mondal.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/supravatm
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/supravat/
  - name: Projects
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects
  - name: Blogs
    icon: <i class="fa-solid fa-blog"></i>
    link: ./blogs
