title: Supravat Mondal
logo: /assets/img/supravat-mondal-logo-picture.webp
email: supravat.com@gmail.com
owner_name: Supravat Mondal
description: SDE @ Open. Adobe-Commerce(Magento 2)
favicon: true
remote_theme: supravatm/jekyll-theme-minimalistic
color-scheme: light
google_analytics: GTM-WSTTQ659
url: "https://github.com/supravatm/"
baseurl: "/"

github:
  is_project_page: true
  owner_url: https://github.com/supravatm/
  owner_name: supravatm

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed

platforms:
  - name: Resume
    icon: <i class="fa-solid fa-file-lines"></i>
    link: https://supravatm.github.io/assets/files/Adobe-Commerce-Engineer-Supravat-Mondal.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/supravatm
  - name: StackOverflow
    icon: <i class="fa-brands fa-stack-overflow"></i>
    link: https://magento.stackexchange.com/users/3368/supravat-mondal
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/supravat/
  - name: Projects
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects.html
  - name: Blogs
    icon: <i class="fa-solid fa-blog"></i>
    link: ./blogs.html
